# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-mock bandit pylint pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest with Coverage report
      run: |
        pytest --cov=. asyncsched/test
    - name: Lint with flake8 Python syntax errors or undefined names
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Lint with flake8
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --ignore=E111 --max-line-length=127 --statistics
    - name: Run Bandit
      run: bandit asyncsched/src asyncsched/test -r -ll --exit-zero
    - name: Run Pylint
      run: pylint asyncsched/src asyncsched/test -r y -d W0311,C0114,C0115,C0116,C0301 --exit-zero